#!/usr/bin/env php
<?php

    // Connecting to DataBase
    define("DATABASE", "db_name");
    define("PASSWORD", "pass");
    define("SERVER", "localhost");
    define("USERNAME", "username");
    $connect=mysqli_connect(SERVER, USERNAME, PASSWORD);

    // Usage of the Command line arguments
    while($argc != 2)
    {
        printf("Usage: ./import /path/to/US.txt\n");
        return false;
    }
    
    // Checking if the file exists and is readable
    if(!file_exists($argv[1]))
    {
        printf("File doesn't exist\n");
        return false;
    }
    else
    if(!is_readable($argv[1]))
    {
        printf("File not readble\n");
        return false;
    }
    
    // Opening the CSV file
    $file = fopen($argv[1],"r"); 
    if(!$file)
    {
        printf("File couldn't be opened\n");
        return false;
    }
    
    $start = microtime(true);
    $num_rows = 0;
    $num_errs = 0;
    // Looping through the whole CSV file and creating array for each row 
    // and then inputting it to SQL tabe
    while (($arr = fgetcsv($file, 0, "\t")) !== FALSE) 
    {
        $num_rows++;
        // Running the insert Query
        $import = query("INSERT INTO `places`(`id`, `country_code`, `postal_code`, 
        `place_name`, `admin_name1`, `admin_code1`, `admin_name2`, `admin_code2`, 
        `admin_name3`, `admin_code3`, `latitude`, `longitude`, `accuracy`) 
        VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", $arr[0], $arr[1],
        $arr[2], $arr[3], $arr[4], $arr[5], $arr[6], $arr[7], $arr[8], $arr[9], $arr[10], $arr[11]);
        if($import === false)
        {
            $num_errs++;
            $num_rows--;  
        }   
    }        
    $time_elapsed_secs = microtime(true) - $start;
    fclose($file);
    printf("Rows Imported : %d\n", $num_rows);
    printf("Errors : %d\n", $num_errs);
    printf("Time Taken : %f sec\n", $time_elapsed_secs);
?>
